sudo: required
language: cpp
compiler: clang
os:
  - linux
  - osx
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi
  - sudo pip install setuptools
  - python setup.py develop
  - sudo pip3 install setuptools
  - python3 setup.py develop
script:
  - scons
notifications:
  email: false
