language: cpp
compiler: clang
os:
  - linux
  - osx
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi
script:
  - scons
  - python setup.py test
  - python3 setup.py test
notifications:
  email: false
