---
language: python # this works for Linux but is an error on macOS or Windows
matrix:
  include:
    - name: "Python 3.5 on Ubuntu 14.04"
      python: 3.5
      before_install: pip3 install scons
    - name: "Python 3.6 on Ubuntu 14.04"
      python: 3.6
      before_install: pip3 install scons
    - name: "Python 3.7 on Ubuntu 16.04"
      python: 3.7
      dist: xenial # required for Python >= 3.7
      before_install: pip3 install scons
    - name: "Python 3.7 on macOS"
      os: osx
      osx_image: xcode10.2 # Python 3.7.2 running on macOS 10.14.3
      language: shell # 'language: python' is an error on Travis CI macOS
      before_install: brew install scons
    - name: "Python 3.7.3 on Windows"
      os: windows # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install: choco install python
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      script:
        - python setup.py sdist
        - python setup.py install
        - python scripts/run.py
# all three OSes agree about 'pip3'
install:
  # - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
script:
  - scons -C nes_py/nes
  - mv nes_py/nes/lib_nes_env*.so nes_py
  - python3 -m unittest discover .
  - python3 setup.py sdist bdist_wheel
notifications:
  email: false
