sudo: required
language: cpp
compiler: clang
os:
  - linux
  - osx
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install scons; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then sudo apt-get install python3 python3-pip; fi
  - sudo pip install -r requirements.txt
  - sudo pip3 install -r requirements.txt
script:
  - scons
notifications:
  email: false
